---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.3.0
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: true
    checksum: true
    download: true
    fetch: true
    git: false
    github: true
    gpg: false
    help: true
    install: true
    package: false
    python: false
    system: true
    tags: true
    version: false
app_desc: a simple CLI tool for creating and managing clusters on EKS - Amazon's managed
    Kubernetes service for EC2.
app_name: eksctl
app_repo: https://github.com/eksctl-io/eksctl
app_type: standalone
app_website: https://eksctl.io/
archive_conf_path: ''
archive_conf_strip: 0
archive_enabled: true
archive_regex: (\\.tar\\.gz|\\.tgz|\\.zip)$
checksum_conf_algorithm: 256
checksum_enabled: true
checksum_url: https://github.com/eksctl-io/eksctl/releases/download/v{version}/eksctl_checksums.txt
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_require_commands: ''
download_url: https://github.com/eksctl-io/eksctl/releases/download/v{version}/eksctl_{os}_{arch}.{ext}
gpg_enabled: false
install_map_enabled: true
install_map_method: move
install_map_yaml:
    eksctl: bin/eksctl
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-eksctl
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-eksctl.git
source_enabled: false
sys_arch_enabled: true
sys_arch_yaml:
    aarch64*: arm64
    armv6*: armv6
    armv7*: armv7
    i386: amd64
    i686: amd64
    powerpc64le: amd4
    ppc64le: amd64
    x86: amd64
    x86_64: amd64
sys_ext_default: tar.gz
sys_ext_enabled: true
sys_ext_yaml:
    windows-*: zip
sys_os_enabled: true
sys_os_yaml:
    darwin: Darwin
    linux: Linux
    windows: Windows
test_cmd_args: version
version_file_enabled: false
version_prefix: v
